---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://BrutalHex.github.io/ops-sample/
    chart: myapp
    targetRevision: 1.x.x
    helm:
      releaseName: mysample
      valuesObject:
        gateway:
          namespace: istio-system
          name: waypoint
          url: web.go.walletpan.com
        s3www:
          nodeSelector: {}
          tolerations: []
          affinity: {}
          replicaCount: 1
          image:
            repository: alpine
            tag: "3.22"
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 300Mi
          deployment:
            labels: {}
            annotations:
              description: s3www serving static bucket content
          podLabels: {}
          podAnnotations: {}
          service:
            port: 8080
            targetPort: 8080
        minio:
          image:
            repository: quay.io/minio/minio
            tag: latest
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 1Gi
              cpu: 1
          replicas: 1
          mode: standalone
          serviceName: myapp-minio
          ## Disable TLS, the mTLS provides secure communication.
          tls:
            enabled: false
          existingSecret: myapp-minio-credentials
          buckets:
            - name: web
              policy: readwrite
              purge: false
              versioning: false
              objectlocking: false
          users: []
          consoleService:
            type: ClusterIP
            port: "9001"
          persistence:
            enabled: true
            size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: test-space
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
